name: Server Refresh

on:
   workflow_dispatch:

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/BlockVisualizer
            pwd
            npm run ssh
